# Generated by Django 2.0.5 on 2018-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=5)),
                ('gst', models.IntegerField(default=5)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
