# Generated by Django 2.0.5 on 2018-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalPrice',
            field=models.IntegerField(default=105),
            preserve_default=False,
        ),
    ]
