# Generated by Django 2.0.5 on 2018-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_product_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
